-- CREATE SCHEMA `pionera_portal` ;

INSERT INTO `pionera_portal`.`boleto_estado` (`id`, `nombre`, `activo`) VALUES ('1', 'Pendiente', '1');
INSERT INTO `pionera_portal`.`boleto_estado` (`id`, `nombre`, `activo`) VALUES ('2', 'Pagado', '1');

INSERT INTO `pionera_portal`.`bus_clase` (`id`, `nombre`, `activo`) VALUES ('1', 'Económica', '1');
INSERT INTO `pionera_portal`.`bus_clase` (`id`, `nombre`, `activo`) VALUES ('2', 'Clase Oro / Maya de Oro', '1');
INSERT INTO `pionera_portal`.`bus_clase` (`id`, `nombre`, `activo`) VALUES ('3', 'Platino / Premier', '1');
INSERT INTO `pionera_portal`.`bus_clase` (`id`, `nombre`, `activo`) VALUES ('4', 'Maya de Oro GL', '1');
INSERT INTO `pionera_portal`.`bus_clase` (`id`, `nombre`, `activo`) VALUES ('5', 'Starbus', '1');
INSERT INTO `pionera_portal`.`bus_clase` (`id`, `nombre`, `activo`) VALUES ('6', 'Clase Oro GL', '1');

INSERT INTO `pionera_portal`.`bus_senal_tipo` (`id`, `nombre`, `activo`) VALUES ('1', 'Puerta', '1');
INSERT INTO `pionera_portal`.`bus_senal_tipo` (`id`, `nombre`, `activo`) VALUES ('2', 'Chofer', '1');

INSERT INTO `pionera_portal`.`clase_asiento` (`id`, `nombre`, `activo`) VALUES ('1', 'A', '1');
INSERT INTO `pionera_portal`.`clase_asiento` (`id`, `nombre`, `activo`) VALUES ('2', 'B', '1');

INSERT INTO `pionera_portal`.`compra_estado` (`id`, `nombre`, `activo`) VALUES ('1', 'Pendiente', '1');
INSERT INTO `pionera_portal`.`compra_estado` (`id`, `nombre`, `activo`) VALUES ('2', 'Pagada', '1');
INSERT INTO `pionera_portal`.`compra_estado` (`id`, `nombre`, `activo`) VALUES ('3', 'Facturada', '1');
INSERT INTO `pionera_portal`.`compra_estado` (`id`, `nombre`, `activo`) VALUES ('4', 'Cancelada', '1');

INSERT INTO `pionera_portal`.`conexion_estado` (`id`, `nombre`, `activo`) VALUES ('1', 'Programada', '1');
INSERT INTO `pionera_portal`.`conexion_estado` (`id`, `nombre`, `activo`) VALUES ('2', 'Abordando', '1');
INSERT INTO `pionera_portal`.`conexion_estado` (`id`, `nombre`, `activo`) VALUES ('3', 'Iniciada', '1');
INSERT INTO `pionera_portal`.`conexion_estado` (`id`, `nombre`, `activo`) VALUES ('4', 'Cancelada', '1');
INSERT INTO `pionera_portal`.`conexion_estado` (`id`, `nombre`, `activo`) VALUES ('5', 'Finalizada', '1');

INSERT INTO `pionera_portal`.`custom_rol` (`nombre`, `descripcion`) VALUES ('ROLE_ADMIN', 'ROLE_ADMIN');
INSERT INTO `pionera_portal`.`custom_rol` (`nombre`, `descripcion`) VALUES ('ROLE_ADMINISTRATIVOS', 'ROLE_ADMINISTRATIVOS');
INSERT INTO `pionera_portal`.`custom_rol` (`nombre`, `descripcion`) VALUES ('ROLE_EDITOR_CONTENIDO', 'ROLE_EDITOR_CONTENIDO');
INSERT INTO `pionera_portal`.`custom_rol` (`nombre`, `descripcion`) VALUES ('ROLE_ENTREGA_COMPRAS', 'ROLE_ENTREGA_COMPRAS');
INSERT INTO `pionera_portal`.`custom_rol` (`nombre`, `descripcion`) VALUES ('ROLE_GESTION_COMPRAS', 'ROLE_GESTION_COMPRAS');
INSERT INTO `pionera_portal`.`custom_rol` (`nombre`, `descripcion`) VALUES ('ROLE_GESTION_CONEXIONES', 'ROLE_GESTION_CONEXIONES');
INSERT INTO `pionera_portal`.`custom_rol` (`nombre`, `descripcion`) VALUES ('ROLE_GESTION_FACTURAS', 'ROLE_GESTION_FACTURAS');
INSERT INTO `pionera_portal`.`custom_rol` (`nombre`, `descripcion`) VALUES ('ROLE_GESTION_ITINERARIOS', 'ROLE_GESTION_ITINERARIOS');
INSERT INTO `pionera_portal`.`custom_rol` (`nombre`, `descripcion`) VALUES ('ROLE_PROPIETARIO', 'ROLE_PROPIETARIO');
INSERT INTO `pionera_portal`.`custom_rol` (`nombre`, `descripcion`) VALUES ('ROLE_REPORTES', 'ROLE_REPORTES');
INSERT INTO `pionera_portal`.`custom_rol` (`nombre`, `descripcion`) VALUES ('ROLE_SUPER_ADMIN', 'ROLE_SUPER_ADMIN');
INSERT INTO `pionera_portal`.`custom_rol` (`nombre`, `descripcion`) VALUES ('ROLE_USER', 'ROLE_USER');

INSERT INTO `pionera_portal`.`custom_user` (`username`, `username_canonical`, `email`, `email_canonical`, `enabled`, `salt`, `password`, `last_login`, `locked`, `expired`, `expires_at`, `roles`, `credentials_expired`, `credentials_expire_at`, `names`, `surnames`, `ipRanges`, `intentosFallidos`, `dateCreate`, `dateLastUdate`, `phone`) VALUES ('javiermarti84', 'javiermarti84', 'javiermarti84@gmail.com', 'javiermarti84@gmail.com', '1', 'ja9qib8eizso8sksk0k84040csk8cg8', 'kDB0q7hNsV0FhN5noczC8kUOnjD/Nq0H6Lw0Nok5c/1KaUAedqtVbNTgjPY9GEiDHyqXXDNJL5uB3j42zwDV3w==', '01/01/2016 10:35:22', '0', '0', '', 'a:11:{i:0;s:10:\"ROLE_ADMIN\";i:1;s:16:\"ROLE_SUPER_ADMIN\";i:2;s:20:\"ROLE_ADMINISTRATIVOS\";i:3;s:21:\"ROLE_EDITOR_CONTENIDO\";i:4;s:23:\"ROLE_GESTION_CONEXIONES\";i:5;s:21:\"ROLE_GESTION_FACTURAS\";i:6;s:24:\"ROLE_GESTION_ITINERARIOS\";i:7;s:16:\"ROLE_PROPIETARIO\";i:8;s:20:\"ROLE_ENTREGA_COMPRAS\";i:9;s:20:\"ROLE_GESTION_COMPRAS\";i:10;s:13:\"ROLE_REPORTES\";}', '0', '21/06/2018 18:51:01', 'Javier', 'Martinez Muñoz', 'a:0:{}', '0', '24/04/2015', '', '11111111');

INSERT INTO `pionera_portal`.`departamento` (`id`, `nombre`, `activo`) VALUES ('1', 'Guatemala', '1');
INSERT INTO `pionera_portal`.`departamento` (`id`, `nombre`, `activo`) VALUES ('2', 'Petén', '1');
INSERT INTO `pionera_portal`.`departamento` (`id`, `nombre`, `activo`) VALUES ('3', 'Huehuetenango', '1');
INSERT INTO `pionera_portal`.`departamento` (`id`, `nombre`, `activo`) VALUES ('4', 'Quiché', '1');
INSERT INTO `pionera_portal`.`departamento` (`id`, `nombre`, `activo`) VALUES ('5', 'Alta Verapaz', '1');
INSERT INTO `pionera_portal`.`departamento` (`id`, `nombre`, `activo`) VALUES ('6', 'Izabal', '1');
INSERT INTO `pionera_portal`.`departamento` (`id`, `nombre`, `activo`) VALUES ('7', 'San Marcos', '1');
INSERT INTO `pionera_portal`.`departamento` (`id`, `nombre`, `activo`) VALUES ('8', 'Quetzaltenango', '1');
INSERT INTO `pionera_portal`.`departamento` (`id`, `nombre`, `activo`) VALUES ('9', 'Totonicapán', '1');
INSERT INTO `pionera_portal`.`departamento` (`id`, `nombre`, `activo`) VALUES ('10', 'Sololá', '1');
INSERT INTO `pionera_portal`.`departamento` (`id`, `nombre`, `activo`) VALUES ('11', 'Chimaltenango', '1');
INSERT INTO `pionera_portal`.`departamento` (`id`, `nombre`, `activo`) VALUES ('12', 'Sacatepéquez', '1');
INSERT INTO `pionera_portal`.`departamento` (`id`, `nombre`, `activo`) VALUES ('13', 'Baja Verapaz', '1');
INSERT INTO `pionera_portal`.`departamento` (`id`, `nombre`, `activo`) VALUES ('14', 'El Progreso', '1');
INSERT INTO `pionera_portal`.`departamento` (`id`, `nombre`, `activo`) VALUES ('15', 'Jalapa', '1');
INSERT INTO `pionera_portal`.`departamento` (`id`, `nombre`, `activo`) VALUES ('16', 'Zacapa', '1');
INSERT INTO `pionera_portal`.`departamento` (`id`, `nombre`, `activo`) VALUES ('17', 'Chiquimula', '1');
INSERT INTO `pionera_portal`.`departamento` (`id`, `nombre`, `activo`) VALUES ('18', 'Retalhuleu', '1');
INSERT INTO `pionera_portal`.`departamento` (`id`, `nombre`, `activo`) VALUES ('19', 'Suchitepéquez', '1');
INSERT INTO `pionera_portal`.`departamento` (`id`, `nombre`, `activo`) VALUES ('20', 'Escuintla', '1');
INSERT INTO `pionera_portal`.`departamento` (`id`, `nombre`, `activo`) VALUES ('21', 'Santa Rosa', '1');
INSERT INTO `pionera_portal`.`departamento` (`id`, `nombre`, `activo`) VALUES ('22', 'Jutiapa', '1');
INSERT INTO `pionera_portal`.`departamento` (`id`, `nombre`, `activo`) VALUES ('23', 'Internacional', '1');

INSERT INTO `pionera_portal`.`dia_semana` (`id`, `nombre`) VALUES ('1', 'Domingo');
INSERT INTO `pionera_portal`.`dia_semana` (`id`, `nombre`) VALUES ('2', 'Lunes');
INSERT INTO `pionera_portal`.`dia_semana` (`id`, `nombre`) VALUES ('3', 'Martes');
INSERT INTO `pionera_portal`.`dia_semana` (`id`, `nombre`) VALUES ('4', 'Miércoles');
INSERT INTO `pionera_portal`.`dia_semana` (`id`, `nombre`) VALUES ('5', 'Jueves');
INSERT INTO `pionera_portal`.`dia_semana` (`id`, `nombre`) VALUES ('6', 'Viernes');
INSERT INTO `pionera_portal`.`dia_semana` (`id`, `nombre`) VALUES ('7', 'Sábado');

INSERT INTO `pionera_portal`.`documento` (`id`, `tipo`) VALUES ('1', 'DPI');
INSERT INTO `pionera_portal`.`documento` (`id`, `tipo`) VALUES ('2', 'Pasaporte Corr');
INSERT INTO `pionera_portal`.`documento` (`id`, `tipo`) VALUES ('3', 'Pasaporte Ofic');
INSERT INTO `pionera_portal`.`documento` (`id`, `tipo`) VALUES ('4', 'Pasaporte Dipl');
INSERT INTO `pionera_portal`.`documento` (`id`, `tipo`) VALUES ('5', 'Pasaporte Prov');
INSERT INTO `pionera_portal`.`documento` (`id`, `tipo`) VALUES ('6', 'Salvo Conducto');
INSERT INTO `pionera_portal`.`documento` (`id`, `tipo`) VALUES ('7', 'Doc. Viaje');
INSERT INTO `pionera_portal`.`documento` (`id`, `tipo`) VALUES ('8', 'Carnet Residente');
INSERT INTO `pionera_portal`.`documento` (`id`, `tipo`) VALUES ('9', 'Cedula');

INSERT INTO `pionera_portal`.`estacion_tipo` (`id`, `nombre`, `activo`) VALUES ('1', 'Estación', '1');
INSERT INTO `pionera_portal`.`estacion_tipo` (`id`, `nombre`, `activo`) VALUES ('2', 'Estación Intermedia', '1');
INSERT INTO `pionera_portal`.`estacion_tipo` (`id`, `nombre`, `activo`) VALUES ('3', 'Recorrido', '1');
INSERT INTO `pionera_portal`.`estacion_tipo` (`id`, `nombre`, `activo`) VALUES ('4', 'Agencia', '1');

INSERT INTO `pionera_portal`.`factura_estado` (`id`, `nombre`) VALUES ('1', 'Creada');
INSERT INTO `pionera_portal`.`factura_estado` (`id`, `nombre`) VALUES ('2', 'Enviada');
INSERT INTO `pionera_portal`.`factura_estado` (`id`, `nombre`) VALUES ('3', 'Recibida');
INSERT INTO `pionera_portal`.`factura_estado` (`id`, `nombre`) VALUES ('4', 'Entregada');

INSERT INTO `pionera_portal`.`Job` (`name`, `serviceId`, `proxy`, `nextExecutionDate`, `insertionDate`, `repeatEvery`, `executionCount`, `status`) VALUES ('Procesar Mensajes', 'acme_backend_mensaje', 'C:41:\"Acme\\BackendBundle\\Scheduled\\DelayedProxy\":6:{a:0:{}}', '2016-03-10 13:00:00', '2016-03-10 00:00:00', '+1 minutes', '0', 'waiting');
INSERT INTO `pionera_portal`.`Job` (`name`, `serviceId`, `proxy`, `nextExecutionDate`, `insertionDate`, `repeatEvery`, `executionCount`, `status`) VALUES ('Syncronizar Datos', 'acme_backend_sincronizar', 'C:41:\"Acme\\BackendBundle\\Scheduled\\DelayedProxy\":6:{a:0:{}}', '2016-03-10 13:00:00', '2016-03-10 00:00:00', '+1 minutes', '0', 'waiting');
INSERT INTO `pionera_portal`.`Job` (`name`, `serviceId`, `proxy`, `nextExecutionDate`, `insertionDate`, `repeatEvery`, `executionCount`, `status`) VALUES ('Conexiones Compuestas', 'acme_backend_conexion', 'C:41:\"Acme\\BackendBundle\\Scheduled\\DelayedProxy\":6:{a:0:{}}', '2016-03-10 13:00:00', '2016-03-10 00:00:00', '+1 month', '0', 'waiting');

INSERT INTO `pionera_portal`.`sexo` (`id`, `sigla`, `nombre`) VALUES ('1', 'M', 'Masculino');
INSERT INTO `pionera_portal`.`sexo` (`id`, `sigla`, `nombre`) VALUES ('2', 'F', 'Femenino');

INSERT INTO `pionera_portal`.`galeria` (`orden`, `nombre`, `referencia`, `activo`) VALUES ('10', 'Banner', 'BANNER', '1');
INSERT INTO `pionera_portal`.`galeria` (`orden`, `nombre`, `referencia`, `descripcion`, `activo`) VALUES ('20', 'Historia', 'HISTORIA', 'En el año de 1959, Don Alfredo Mendoza Pellicer, tuvo la iniciativa de fomentar una pequeña empresa familiar de transporte, conjuntamente con su Sra. Esposa, esto debido a que existía una necesidad de un transporte de la aldea de Mariscos al cruce de Trincheras, ante esta posibilidad la familia Mendoza Pellicer, inicio con una modesta camioneta de 3 asientos, de Mariscos a la aldea de Los Amates y de aldea Mariscos a la Cabecera departamental de Izabal, Puerto Barrios.', '1');
INSERT INTO `pionera_portal`.`galeria` (`orden`, `nombre`, `referencia`, `descripcion`, `activo`) VALUES ('30', 'CLASE ORO GRAN LUJO', 'SERVICIO-BOLETO', 'La flota 2015 de autobuses Clase Oro Gran Lujo, de Transportes Fuente del Norte la Pionera, son una distintiva forma de viajar en Guatemala, una mescla de Confort, Gran Lujo y Esparcimiento, nuestras unidades cuentan con servicio de Wi-Fi para Redes, Servicio con 2 Baños,  Aire Acondicionado,  Luces De Lectura Individual, Monitores con películas en sonido Estéreo con audífonos integrados personalizados, asientos Todo Confort, Planta Alta de 48 asientos y Planta Baja Ejecutiva con 12 asientos de Gran Lujo Semi-cama de Piel, para que mientras usted descansa nosotros lo llevamos hasta su destino, Ventanas Panorámicas, Servicio Eléctrico para recargar su teléfono o Laptop individual por asiento, Servicio de amplitud de Cajuelas de Equipaje, Seguro de Viajero, Control de Velocidad automática, 2 Pilotos Certificados Profesionales, contamos con 3 suspensiones para mayor estabilidad y la Seguridad que usted disfruta al viajar con nosotros. Servicio Clase Oro Gran Lujo, una experiencia diferente de viajar a su altura.', '1');
INSERT INTO `pionera_portal`.`galeria` (`orden`, `nombre`, `referencia`, `descripcion`, `activo`) VALUES ('40', 'MAYA DE ORO GRAN LUJO', 'SERVICIO-BOLETO', 'Buses doble piso del 2015 con servicios de aire acondicionado, televisión con control de audio personalizado, WIFI, asientos semi camas y dos baños.', '0');
INSERT INTO `pionera_portal`.`galeria` (`orden`, `nombre`, `referencia`, `descripcion`, `activo`) VALUES ('50', 'CLASE ORO', 'SERVICIO-BOLETO', 'Los Autobuses Servicio Clase Oro, son ideales para sus viajes de negocios o de placer, cuentan con dos niveles para su mayor comodidad, en la parte superior contamos con  confortables asientos reclinables, luces de lectura individual, mientras que en la parte baja contamos con 9 asientos semi-cama, para que su viaje sea más placentero, Servicio de Aire Acondicionado, Baño, monitores en ambos niveles, con películas selectas y familiares, 2 Pilotos Certificados Profesionales, Seguro de Viajero, amplitud de cajuelas de equipaje, en Servicio Clase Oro su Viaje es cómodo y puntual.', '1');
INSERT INTO `pionera_portal`.`galeria` (`orden`, `nombre`, `referencia`, `descripcion`, `activo`) VALUES ('60', 'MAYA DE ORO', 'SERVICIO-BOLETO', 'Buses con servicios de aire acondicionado, televisión, WIFI y baño.', '0');
INSERT INTO `pionera_portal`.`galeria` (`orden`, `nombre`, `referencia`, `descripcion`, `activo`) VALUES ('70', 'PLATINO', 'SERVICIO-BOLETO', 'El Servicio Platino de Transportes Fuente del Norte La Pionera, es el mismo esmerado servicio que nos distingue, con autobuses modernos y confortables de Primera Clase, con asientos cómodos y reclinables, servicio con aire acondicionado automatizado, luces de lectura individual, ventanas panorámicas, Seguro de Viajera, pilotos certificados profesionales, en Servicio Platino, lo llevamos a su punto de destino con Prontitud, Seguridad y Confort.', '1');
INSERT INTO `pionera_portal`.`galeria` (`orden`, `nombre`, `referencia`, `descripcion`, `activo`) VALUES ('80', 'PREMIER', 'SERVICIO-BOLETO', 'Buses con servicios de aire acondicionado y baño.', '0');
INSERT INTO `pionera_portal`.`galeria` (`orden`, `nombre`, `referencia`, `descripcion`, `activo`) VALUES ('90', 'STARBUS', 'SERVICIO-BOLETO', 'Buses de un nivel con servicios de aire acondicionado, televisión y baño.', '0');
INSERT INTO `pionera_portal`.`galeria` (`orden`, `nombre`, `referencia`, `descripcion`, `activo`) VALUES ('100', 'ECONOMICO', 'SERVICIO-BOLETO', 'Nuestro Servicio Económico de Transportes Fuente del Norte, lo conecta a cualquier punto de Guatemala, con autobuses cómodos y seguros, tenemos presencia en todo el país de frontera a frontera, por eso nuestra empresa pensando en las familias chapinas, le ofrece el servicio de Servicio Económico, para que usted pueda viajar cuidando su economía y la de los suyos, contamos con asientos individuales, seguro de viajero y la seguridad que nos distingue.', '1');
INSERT INTO `pionera_portal`.`galeria` (`orden`, `nombre`, `referencia`, `descripcion`, `activo`) VALUES ('110', 'ENCOMIENDAS', 'SERVICIO-ENCOMIENDAS', 'En nuestro país de Guatemala, los Servicios de Encomienda de Transportes Fuente del Norte, lo acercan cada vez más, ofreciéndole un servicio de paquetería, encomiendas y todo lo que necesitas mandar a los tuyos o tu empresa, en forma segura, honesta, rápida y puntual. Le respaldamos su encomienda con la profesionalidad de más de 55 años de nuestra empresa, nuestros precios son los más bajos de todo Guatemala. Pregunte por nuestros servicios de encomienda, en cualquier estación de Transportes Fuente Del Norte La Pionera.', '1');
INSERT INTO `pionera_portal`.`galeria` (`orden`, `nombre`, `referencia`, `descripcion`, `activo`) VALUES ('120', 'RENTA DE AUTOBUSES O EXCURSIONES', 'SERVICIO-EXCURSIONES', 'Los mejores planes de viajes colectivos, se vuelven una experiencia agradable, rentando un autobús de Transportes Fuente Del Norte La Pionera, nos ajustamos a su presupuesto según sus necesidades, Excursiones escolares, de negocios, de trabajo o de esparcimiento. Contamos con una flota de Autobuses con aire acondicionado, equipados con todo servicio, o económicos según sea su viaje. También contamos con autobuses para rentar, visite a nuestro personal autorizado o contáctenos sin compromiso a los teléfonos 00 (502) 7947 7070, será un gusto atenderles.', '1');
INSERT INTO `pionera_portal`.`galeria` (`orden`, `nombre`, `referencia`, `activo`) VALUES ('130', 'Publicidad', 'PUBLICIDAD', '1');
INSERT INTO `pionera_portal`.`galeria` (`orden`, `nombre`, `referencia`, `activo`) VALUES ('140', 'HOME', 'HOME', '1');


INSERT INTO `pionera_portal`.`nacionalidad` (`id`, `nombre`, `activo`) VALUES ('1', 'Angoleña', '1');
INSERT INTO `pionera_portal`.`nacionalidad` (`id`, `nombre`, `activo`) VALUES ('2', 'Argelina', '1');
INSERT INTO `pionera_portal`.`nacionalidad` (`id`, `nombre`, `activo`) VALUES ('3', 'Camerunesa', '1');
INSERT INTO `pionera_portal`.`nacionalidad` (`id`, `nombre`, `activo`) VALUES ('4', 'Etíope', '1');
INSERT INTO `pionera_portal`.`nacionalidad` (`id`, `nombre`, `activo`) VALUES ('5', 'Ecuatoguineana', '1');
INSERT INTO `pionera_portal`.`nacionalidad` (`id`, `nombre`, `activo`) VALUES ('6', 'Egipcia', '1');
INSERT INTO `pionera_portal`.`nacionalidad` (`id`, `nombre`, `activo`) VALUES ('7', 'Liberiana', '1');
INSERT INTO `pionera_portal`.`nacionalidad` (`id`, `nombre`, `activo`) VALUES ('8', 'Libia', '1');
INSERT INTO `pionera_portal`.`nacionalidad` (`id`, `nombre`, `activo`) VALUES ('9', 'Marroquí', '1');
INSERT INTO `pionera_portal`.`nacionalidad` (`id`, `nombre`, `activo`) VALUES ('10', 'Namibia', '1');
INSERT INTO `pionera_portal`.`nacionalidad` (`id`, `nombre`, `activo`) VALUES ('11', 'Nigeriana', '1');
INSERT INTO `pionera_portal`.`nacionalidad` (`id`, `nombre`, `activo`) VALUES ('12', 'Saharaui', '1');
INSERT INTO `pionera_portal`.`nacionalidad` (`id`, `nombre`, `activo`) VALUES ('13', 'Senegalesa', '1');
INSERT INTO `pionera_portal`.`nacionalidad` (`id`, `nombre`, `activo`) VALUES ('14', 'Sudafricana', '1');
INSERT INTO `pionera_portal`.`nacionalidad` (`id`, `nombre`, `activo`) VALUES ('15', 'Togolesa', '1');
INSERT INTO `pionera_portal`.`nacionalidad` (`id`, `nombre`, `activo`) VALUES ('16', 'Canadiense', '1');
INSERT INTO `pionera_portal`.`nacionalidad` (`id`, `nombre`, `activo`) VALUES ('17', 'Estadounidense', '1');
INSERT INTO `pionera_portal`.`nacionalidad` (`id`, `nombre`, `activo`) VALUES ('18', 'Mexicana', '1');
INSERT INTO `pionera_portal`.`nacionalidad` (`id`, `nombre`, `activo`) VALUES ('19', 'Beliceña', '1');
INSERT INTO `pionera_portal`.`nacionalidad` (`id`, `nombre`, `activo`) VALUES ('20', 'Costarricense', '1');
INSERT INTO `pionera_portal`.`nacionalidad` (`id`, `nombre`, `activo`) VALUES ('21', 'Guatemalteca', '1');
INSERT INTO `pionera_portal`.`nacionalidad` (`id`, `nombre`, `activo`) VALUES ('22', 'Hondureña', '1');
INSERT INTO `pionera_portal`.`nacionalidad` (`id`, `nombre`, `activo`) VALUES ('23', 'Nicaragüense', '1');
INSERT INTO `pionera_portal`.`nacionalidad` (`id`, `nombre`, `activo`) VALUES ('24', 'Panameña', '1');
INSERT INTO `pionera_portal`.`nacionalidad` (`id`, `nombre`, `activo`) VALUES ('25', 'Salvadoreña', '1');
INSERT INTO `pionera_portal`.`nacionalidad` (`id`, `nombre`, `activo`) VALUES ('26', 'Cubana', '1');
INSERT INTO `pionera_portal`.`nacionalidad` (`id`, `nombre`, `activo`) VALUES ('27', 'Arubana', '1');
INSERT INTO `pionera_portal`.`nacionalidad` (`id`, `nombre`, `activo`) VALUES ('28', 'Bahameña', '1');
INSERT INTO `pionera_portal`.`nacionalidad` (`id`, `nombre`, `activo`) VALUES ('29', 'Barbadense', '1');
INSERT INTO `pionera_portal`.`nacionalidad` (`id`, `nombre`, `activo`) VALUES ('30', 'Dominiquesa', '1');
INSERT INTO `pionera_portal`.`nacionalidad` (`id`, `nombre`, `activo`) VALUES ('31', 'Dominicana', '1');
INSERT INTO `pionera_portal`.`nacionalidad` (`id`, `nombre`, `activo`) VALUES ('32', 'Haitiana', '1');
INSERT INTO `pionera_portal`.`nacionalidad` (`id`, `nombre`, `activo`) VALUES ('33', 'Jamaiquina', '1');
INSERT INTO `pionera_portal`.`nacionalidad` (`id`, `nombre`, `activo`) VALUES ('34', 'Puertorriqueña', '1');
INSERT INTO `pionera_portal`.`nacionalidad` (`id`, `nombre`, `activo`) VALUES ('35', 'Sancristobaleña', '1');
INSERT INTO `pionera_portal`.`nacionalidad` (`id`, `nombre`, `activo`) VALUES ('36', 'Santaluciana', '1');
INSERT INTO `pionera_portal`.`nacionalidad` (`id`, `nombre`, `activo`) VALUES ('37', 'Sanvicentina', '1');
INSERT INTO `pionera_portal`.`nacionalidad` (`id`, `nombre`, `activo`) VALUES ('38', 'Argentina', '1');
INSERT INTO `pionera_portal`.`nacionalidad` (`id`, `nombre`, `activo`) VALUES ('39', 'Boliviana', '1');
INSERT INTO `pionera_portal`.`nacionalidad` (`id`, `nombre`, `activo`) VALUES ('40', 'Brasileña', '1');
INSERT INTO `pionera_portal`.`nacionalidad` (`id`, `nombre`, `activo`) VALUES ('41', 'Chilena', '1');
INSERT INTO `pionera_portal`.`nacionalidad` (`id`, `nombre`, `activo`) VALUES ('42', 'Colombiana', '1');
INSERT INTO `pionera_portal`.`nacionalidad` (`id`, `nombre`, `activo`) VALUES ('43', 'Ecuatoriana', '1');
INSERT INTO `pionera_portal`.`nacionalidad` (`id`, `nombre`, `activo`) VALUES ('44', 'Guyanés', '1');
INSERT INTO `pionera_portal`.`nacionalidad` (`id`, `nombre`, `activo`) VALUES ('45', 'Paraguaya', '1');
INSERT INTO `pionera_portal`.`nacionalidad` (`id`, `nombre`, `activo`) VALUES ('46', 'Peruana', '1');
INSERT INTO `pionera_portal`.`nacionalidad` (`id`, `nombre`, `activo`) VALUES ('47', 'Surinamés', '1');
INSERT INTO `pionera_portal`.`nacionalidad` (`id`, `nombre`, `activo`) VALUES ('48', 'Uruguaya', '1');
INSERT INTO `pionera_portal`.`nacionalidad` (`id`, `nombre`, `activo`) VALUES ('49', 'Venezolana', '1');
INSERT INTO `pionera_portal`.`nacionalidad` (`id`, `nombre`, `activo`) VALUES ('50', 'Afgana', '1');
INSERT INTO `pionera_portal`.`nacionalidad` (`id`, `nombre`, `activo`) VALUES ('51', 'Azerbaiyana', '1');
INSERT INTO `pionera_portal`.`nacionalidad` (`id`, `nombre`, `activo`) VALUES ('52', 'Bangladesí', '1');
INSERT INTO `pionera_portal`.`nacionalidad` (`id`, `nombre`, `activo`) VALUES ('53', 'Bareiní', '1');
INSERT INTO `pionera_portal`.`nacionalidad` (`id`, `nombre`, `activo`) VALUES ('54', 'China', '1');
INSERT INTO `pionera_portal`.`nacionalidad` (`id`, `nombre`, `activo`) VALUES ('55', 'Filipina', '1');
INSERT INTO `pionera_portal`.`nacionalidad` (`id`, `nombre`, `activo`) VALUES ('56', 'Georgiana', '1');
INSERT INTO `pionera_portal`.`nacionalidad` (`id`, `nombre`, `activo`) VALUES ('57', 'Hindú', '1');
INSERT INTO `pionera_portal`.`nacionalidad` (`id`, `nombre`, `activo`) VALUES ('58', 'Indonesia', '1');
INSERT INTO `pionera_portal`.`nacionalidad` (`id`, `nombre`, `activo`) VALUES ('59', 'Israelí', '1');
INSERT INTO `pionera_portal`.`nacionalidad` (`id`, `nombre`, `activo`) VALUES ('60', 'Japonesa', '1');
INSERT INTO `pionera_portal`.`nacionalidad` (`id`, `nombre`, `activo`) VALUES ('61', 'Libanesa', '1');
INSERT INTO `pionera_portal`.`nacionalidad` (`id`, `nombre`, `activo`) VALUES ('62', 'Mongola', '1');
INSERT INTO `pionera_portal`.`nacionalidad` (`id`, `nombre`, `activo`) VALUES ('63', 'Norcoreana', '1');
INSERT INTO `pionera_portal`.`nacionalidad` (`id`, `nombre`, `activo`) VALUES ('64', 'Siria', '1');
INSERT INTO `pionera_portal`.`nacionalidad` (`id`, `nombre`, `activo`) VALUES ('65', 'Surcoreana', '1');
INSERT INTO `pionera_portal`.`nacionalidad` (`id`, `nombre`, `activo`) VALUES ('66', 'Vietnamita', '1');
INSERT INTO `pionera_portal`.`nacionalidad` (`id`, `nombre`, `activo`) VALUES ('67', 'Europea', '1');
INSERT INTO `pionera_portal`.`nacionalidad` (`id`, `nombre`, `activo`) VALUES ('68', 'Albanesa', '1');
INSERT INTO `pionera_portal`.`nacionalidad` (`id`, `nombre`, `activo`) VALUES ('69', 'Alemana', '1');
INSERT INTO `pionera_portal`.`nacionalidad` (`id`, `nombre`, `activo`) VALUES ('70', 'Andorrana', '1');
INSERT INTO `pionera_portal`.`nacionalidad` (`id`, `nombre`, `activo`) VALUES ('71', 'Armenia', '1');
INSERT INTO `pionera_portal`.`nacionalidad` (`id`, `nombre`, `activo`) VALUES ('72', 'Austríaca', '1');
INSERT INTO `pionera_portal`.`nacionalidad` (`id`, `nombre`, `activo`) VALUES ('73', 'Belga', '1');
INSERT INTO `pionera_portal`.`nacionalidad` (`id`, `nombre`, `activo`) VALUES ('74', 'Bielorrusa', '1');
INSERT INTO `pionera_portal`.`nacionalidad` (`id`, `nombre`, `activo`) VALUES ('75', 'Bosnia', '1');
INSERT INTO `pionera_portal`.`nacionalidad` (`id`, `nombre`, `activo`) VALUES ('76', 'Búlgara', '1');
INSERT INTO `pionera_portal`.`nacionalidad` (`id`, `nombre`, `activo`) VALUES ('77', 'Checa', '1');
INSERT INTO `pionera_portal`.`nacionalidad` (`id`, `nombre`, `activo`) VALUES ('78', 'Chipriota', '1');
INSERT INTO `pionera_portal`.`nacionalidad` (`id`, `nombre`, `activo`) VALUES ('79', 'Croata', '1');
INSERT INTO `pionera_portal`.`nacionalidad` (`id`, `nombre`, `activo`) VALUES ('80', 'Danesa', '1');
INSERT INTO `pionera_portal`.`nacionalidad` (`id`, `nombre`, `activo`) VALUES ('81', 'Escocesa', '1');
INSERT INTO `pionera_portal`.`nacionalidad` (`id`, `nombre`, `activo`) VALUES ('82', 'Eslovaca', '1');
INSERT INTO `pionera_portal`.`nacionalidad` (`id`, `nombre`, `activo`) VALUES ('83', 'Eslovena', '1');
INSERT INTO `pionera_portal`.`nacionalidad` (`id`, `nombre`, `activo`) VALUES ('84', 'Española', '1');
INSERT INTO `pionera_portal`.`nacionalidad` (`id`, `nombre`, `activo`) VALUES ('85', 'Estonia', '1');
INSERT INTO `pionera_portal`.`nacionalidad` (`id`, `nombre`, `activo`) VALUES ('86', 'Finlandesa', '1');
INSERT INTO `pionera_portal`.`nacionalidad` (`id`, `nombre`, `activo`) VALUES ('87', 'Francesa', '1');
INSERT INTO `pionera_portal`.`nacionalidad` (`id`, `nombre`, `activo`) VALUES ('88', 'Griega', '1');
INSERT INTO `pionera_portal`.`nacionalidad` (`id`, `nombre`, `activo`) VALUES ('89', 'Húngara', '1');
INSERT INTO `pionera_portal`.`nacionalidad` (`id`, `nombre`, `activo`) VALUES ('90', 'Británica', '1');
INSERT INTO `pionera_portal`.`nacionalidad` (`id`, `nombre`, `activo`) VALUES ('91', 'Irlandesa', '1');
INSERT INTO `pionera_portal`.`nacionalidad` (`id`, `nombre`, `activo`) VALUES ('92', 'Italiana', '1');
INSERT INTO `pionera_portal`.`nacionalidad` (`id`, `nombre`, `activo`) VALUES ('93', 'Letona', '1');
INSERT INTO `pionera_portal`.`nacionalidad` (`id`, `nombre`, `activo`) VALUES ('94', 'Lituana', '1');
INSERT INTO `pionera_portal`.`nacionalidad` (`id`, `nombre`, `activo`) VALUES ('95', 'Luxemburguesa', '1');
INSERT INTO `pionera_portal`.`nacionalidad` (`id`, `nombre`, `activo`) VALUES ('96', 'Maltesa', '1');
INSERT INTO `pionera_portal`.`nacionalidad` (`id`, `nombre`, `activo`) VALUES ('97', 'Moldava', '1');
INSERT INTO `pionera_portal`.`nacionalidad` (`id`, `nombre`, `activo`) VALUES ('98', 'Monegasca', '1');
INSERT INTO `pionera_portal`.`nacionalidad` (`id`, `nombre`, `activo`) VALUES ('99', 'Montenegrina', '1');
INSERT INTO `pionera_portal`.`nacionalidad` (`id`, `nombre`, `activo`) VALUES ('100', 'Noruega', '1');
INSERT INTO `pionera_portal`.`nacionalidad` (`id`, `nombre`, `activo`) VALUES ('101', 'Neerlandesa', '1');
INSERT INTO `pionera_portal`.`nacionalidad` (`id`, `nombre`, `activo`) VALUES ('102', 'Polaca', '1');
INSERT INTO `pionera_portal`.`nacionalidad` (`id`, `nombre`, `activo`) VALUES ('103', 'Portuguesa', '1');
INSERT INTO `pionera_portal`.`nacionalidad` (`id`, `nombre`, `activo`) VALUES ('104', 'Rumana', '1');
INSERT INTO `pionera_portal`.`nacionalidad` (`id`, `nombre`, `activo`) VALUES ('105', 'Rusa', '1');
INSERT INTO `pionera_portal`.`nacionalidad` (`id`, `nombre`, `activo`) VALUES ('106', 'Serbia', '1');
INSERT INTO `pionera_portal`.`nacionalidad` (`id`, `nombre`, `activo`) VALUES ('107', 'Sueca', '1');
INSERT INTO `pionera_portal`.`nacionalidad` (`id`, `nombre`, `activo`) VALUES ('108', 'Suiza', '1');
INSERT INTO `pionera_portal`.`nacionalidad` (`id`, `nombre`, `activo`) VALUES ('109', 'Turca', '1');
INSERT INTO `pionera_portal`.`nacionalidad` (`id`, `nombre`, `activo`) VALUES ('110', 'Ucraniana', '1');
INSERT INTO `pionera_portal`.`nacionalidad` (`id`, `nombre`, `activo`) VALUES ('111', 'Australiana', '1');
INSERT INTO `pionera_portal`.`nacionalidad` (`id`, `nombre`, `activo`) VALUES ('112', 'Neozelandesa', '1');
INSERT INTO `pionera_portal`.`nacionalidad` (`id`, `nombre`, `activo`) VALUES ('113', 'Británica (Escocia, Inglaterra, Gales)', '1');
INSERT INTO `pionera_portal`.`nacionalidad` (`id`, `nombre`, `activo`) VALUES ('114', 'Samoamericana', '1');
INSERT INTO `pionera_portal`.`nacionalidad` (`id`, `nombre`, `activo`) VALUES ('115', 'Anguilense', '1');
INSERT INTO `pionera_portal`.`nacionalidad` (`id`, `nombre`, `activo`) VALUES ('116', 'Antiguana', '1');
INSERT INTO `pionera_portal`.`nacionalidad` (`id`, `nombre`, `activo`) VALUES ('117', 'Bahrein', '1');
INSERT INTO `pionera_portal`.`nacionalidad` (`id`, `nombre`, `activo`) VALUES ('118', 'Antártica', '1');

INSERT INTO `Job` (`id`,`name`,`serviceId`,`proxy`,`nextExecutionDate`,`insertionDate`,`firstExecutionDate`,`lastExecutionDate`,`repeatEvery`,`executionCount`,`status`,`lastException`) VALUES (1,'Procesar Mensajes','acme_backend_mensaje','C:41:\"Acme\\BackendBundle\\Scheduled\\DelayedProxy\":6:{a:0:{}}','2017-03-10 13:00:00','0000-00-00 00:00:00','0000-00-00 00:00:00',NULL,'+1 minutes',0,'waiting',NULL);
INSERT INTO `Job` (`id`,`name`,`serviceId`,`proxy`,`nextExecutionDate`,`insertionDate`,`firstExecutionDate`,`lastExecutionDate`,`repeatEvery`,`executionCount`,`status`,`lastException`) VALUES (2,'Syncronizar Datos Job','acme_backend_sincronizar1','C:41:\"Acme\\BackendBundle\\Scheduled\\DelayedProxy\":6:{a:0:{}}','2016-03-11 21:02:00','0000-00-00 00:00:00','0000-00-00 00:00:00','2016-03-14 16:19:11','+1 minutes',0,'waiting',NULL);
INSERT INTO `Job` (`id`,`name`,`serviceId`,`proxy`,`nextExecutionDate`,`insertionDate`,`firstExecutionDate`,`lastExecutionDate`,`repeatEvery`,`executionCount`,`status`,`lastException`) VALUES (3,'Conexiones Compuestas','acme_backend_conexion','C:41:\"Acme\\BackendBundle\\Scheduled\\DelayedProxy\":6:{a:0:{}}','2017-03-10 13:00:00','0000-00-00 00:00:00','0000-00-00 00:00:00',NULL,'+1 month',0,'waiting',NULL);
INSERT INTO `Job` (`id`,`name`,`serviceId`,`proxy`,`nextExecutionDate`,`insertionDate`,`firstExecutionDate`,`lastExecutionDate`,`repeatEvery`,`executionCount`,`status`,`lastException`) VALUES (4,'Syncronizar Datos Salida','acme_backend_sincronizar2','C:41:\"Acme\\BackendBundle\\Scheduled\\DelayedProxy\":6:{a:0:{}}','2016-03-11 21:02:00','0000-00-00 00:00:00','0000-00-00 00:00:00','2016-03-14 16:19:11','+5 minutes',0,'waiting',NULL);

UPDATE `pionera_portal`.`estacion` SET `facturacion`='1' WHERE `id`='1';
UPDATE `pionera_portal`.`estacion` SET `facturacion`='1' WHERE `id`='2';
UPDATE `pionera_portal`.`estacion` SET `facturacion`='1' WHERE `id`='3';
UPDATE `pionera_portal`.`estacion` SET `facturacion`='1' WHERE `id`='5';
UPDATE `pionera_portal`.`estacion` SET `facturacion`='1' WHERE `id`='4';
UPDATE `pionera_portal`.`estacion` SET `facturacion`='1' WHERE `id`='12';
UPDATE `pionera_portal`.`estacion` SET `facturacion`='1' WHERE `id`='13';
