imports:
    - { resource: config.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: false
    intercept_redirects: false

monolog:
    handlers:
#        main:
#            type:  stream
#            path:  "%kernel.logs_dir%/%kernel.environment%.log"
#            level: info
#        firephp:
#            type:  firephp
#            level: info
#        chromephp:
#            type:  chromephp
#            level: info
        commands:
            type:  rotating_file
            path:  %kernel.logs_dir%/%kernel.environment%.log
            action_level: info
            channels: [app]

assetic:
    use_controller: false

#swiftmailer:
#    delivery_address: me@example.com
