imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: hwio.yml }
    - { resource: services.yml }
    - { resource: sonata.yml }
    - { resource: ivory.yml }
    - { resource: google.yml }

fos_user:
    db_driver: orm
    firewall_name: admin_secured_area
    user_class: Acme\BackendBundle\Entity\User
        
framework:
    #esi:             ~
    translator:      { enabled: true, fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          false
    use_controller: false
    bundles:        [ MayaBundle, BackendBundle ]
    java: C:\Program Files\Java\jre7\bin\java.exe
    filters:
        cssrewrite: ~
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        yui_css:
            jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar
        yui_js:
            jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
#    spool:     { type: memory }

ewz_recaptcha:
    public_key: "%recaptcha_public_key%"
    private_key: "%recaptcha_private_key%"
    locale_key:  locale
    secure: false
    enabled: true

monolog: 
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested      
        nested:
            type:  rotating_file
            path:  %kernel.logs_dir%/%kernel.environment%.log
            level: info